package kuntosali.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kuntosali.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.19 15:42:09 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AsiakasTest {



  // Generated by ComTest BEGIN
  /** testGetNimi49 */
  @Test
  public void testGetNimi49() {    // Asiakas: 49
    Asiakas asiakas = new Asiakas(); 
    asiakas.taytaAsiakas(); 
    { String _l_=asiakas.getNimi(),_r_="Ismo Laitela .*"; if ( !_l_.matches(_r_) ) fail("From: Asiakas line: 52" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi105 */
  @Test
  public void testRekisteroi105() {    // Asiakas: 105
    Asiakas testi1 = new Asiakas(); 
    assertEquals("From: Asiakas line: 107", 0, testi1.getTunnusNro()); 
    testi1.rekisteroi(); 
    Asiakas testi2 = new Asiakas(); 
    testi2.rekisteroi(); 
    int n1 = testi1.getTunnusNro(); 
    int n2 = testi2.getTunnusNro(); 
    assertEquals("From: Asiakas line: 113", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString135 */
  @Test
  public void testToString135() {    // Asiakas: 135
    Asiakas asiakas = new Asiakas(); 
    asiakas.parse("   3  |  Ankka Aku   | 030201-111C"); 
    assertEquals("From: Asiakas line: 138", true, asiakas.toString().startsWith("3|Ankka Aku|030201-111C|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse163 */
  @Test
  public void testParse163() {    // Asiakas: 163
    Asiakas asiakas = new Asiakas(); 
    asiakas.parse("   3  |  Ankka Aku   | 030201-111C"); 
    assertEquals("From: Asiakas line: 166", 3, asiakas.getTunnusNro()); 
    assertEquals("From: Asiakas line: 167", true, asiakas.toString().startsWith("3|Ankka Aku|030201-111C|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    asiakas.rekisteroi(); 
    int n = asiakas.getTunnusNro(); 
    asiakas.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    asiakas.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Asiakas line: 173", n+20+1, asiakas.getTunnusNro()); 
  } // Generated by ComTest END
}