package kuntosali.test;
// Generated by ComTest BEGIN
import kuntosali.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.08.03 13:47:03 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KuntosaliTest {



  // Generated by ComTest BEGIN
  /** testAsiakkuusLoppumassa171 */
  @Test
  public void testAsiakkuusLoppumassa171() {    // Kuntosali: 171
    Kuntosali kuntosali = new Kuntosali(); 
    Asiakas asiakas = new Asiakas(); 
    Asiakas asiakas1 = new Asiakas(); 
    Asiakas asiakas2 = new Asiakas(); 
    asiakas1.parse("5|Kari Taalasmaa|0402470506|Kahvakuulantie 7|56700|Kangasala|kari.taalasmaa@hotmail.com|2018-02-23|2020-11-24"); 
    asiakas.parse("6|Seppo Taalasmaa|0405330207|Kalliokuja 21|56700|Helsinki|seppo.ukko@hotmail.com|2017-12-01|2020-06-01"); 
    asiakas2.parse("2|Koira Ukko|0123456789|Koirakuja 7|63700|Koirakyla|koiruli@koiramail.com|1998-06-21|2020-08-05"); 
    assertEquals("From: Kuntosali line: 181", -63, kuntosali.asiakkuusLoppumassa(asiakas)); 
    assertEquals("From: Kuntosali line: 182", 113, kuntosali.asiakkuusLoppumassa(asiakas1)); 
    assertEquals("From: Kuntosali line: 183", 2, kuntosali.asiakkuusLoppumassa(asiakas2)); 
  } // Generated by ComTest END
}