package kuntosali.test;
// Generated by ComTest BEGIN
import kuntosali.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.21 11:52:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RyhmaliikunnatTest {


  // Generated by ComTest BEGIN
  /** testIterator143 */
  @Test
  public void testIterator143() {    // Ryhmaliikunnat: 143
    Ryhmaliikunnat ryhmat = new Ryhmaliikunnat(); 
    Ryhmaliikunta pitsi21 = new Ryhmaliikunta(2); ryhmat.lisaa(pitsi21); 
    Ryhmaliikunta pitsi11 = new Ryhmaliikunta(1); ryhmat.lisaa(pitsi11); 
    Ryhmaliikunta pitsi22 = new Ryhmaliikunta(2); ryhmat.lisaa(pitsi22); 
    Ryhmaliikunta pitsi12 = new Ryhmaliikunta(1); ryhmat.lisaa(pitsi12); 
    Ryhmaliikunta pitsi23 = new Ryhmaliikunta(2); ryhmat.lisaa(pitsi23); 
    Iterator<Ryhmaliikunta> i2=ryhmat.iterator(); 
    assertEquals("From: Ryhmaliikunnat line: 155", pitsi21, i2.next()); 
    assertEquals("From: Ryhmaliikunnat line: 156", pitsi11, i2.next()); 
    assertEquals("From: Ryhmaliikunnat line: 157", pitsi22, i2.next()); 
    assertEquals("From: Ryhmaliikunnat line: 158", pitsi12, i2.next()); 
    assertEquals("From: Ryhmaliikunnat line: 159", pitsi23, i2.next()); 
    try {
    assertEquals("From: Ryhmaliikunnat line: 160", pitsi12, i2.next()); 
    fail("Ryhmaliikunnat: 160 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int anrot[] = { 2,1,2,1,2} ; 
    for ( Ryhmaliikunta ryhma:ryhmat ) {
    assertEquals("From: Ryhmaliikunnat line: 166", anrot[n], ryhma.getAsiakasNro()); n++; 
    }
    assertEquals("From: Ryhmaliikunnat line: 169", 5, n); 
  } // Generated by ComTest END
}