package kuntosali.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kuntosali.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.08.02 19:13:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RyhmaliikuntaTest {



  // Generated by ComTest BEGIN
  /** testAseta58 */
  @Test
  public void testAseta58() {    // Ryhmaliikunta: 58
    Ryhmaliikunta jasen = new Ryhmaliikunta(); 
    assertEquals("From: Ryhmaliikunta line: 60", null, jasen.aseta(2,"Ankka")); 
    assertEquals("From: Ryhmaliikunta line: 61", null, jasen.aseta(3,"maanantai")); 
    assertEquals("From: Ryhmaliikunta line: 62", "Anna muodossa 15.30-16.00", jasen.aseta(4,"63.00-17.00")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi161 */
  @Test
  public void testRekisteroi161() {    // Ryhmaliikunta: 161
    Ryhmaliikunta testi1 = new Ryhmaliikunta(); 
    assertEquals("From: Ryhmaliikunta line: 163", 0, testi1.getTunnusNro()); 
    testi1.rekisteroi(); 
    Ryhmaliikunta testi2 = new Ryhmaliikunta(); 
    testi2.rekisteroi(); 
    int n1 = testi1.getTunnusNro(); 
    int n2 = testi2.getTunnusNro(); 
    assertEquals("From: Ryhmaliikunta line: 169", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse229 */
  @Test
  public void testParse229() {    // Ryhmaliikunta: 229
    Ryhmaliikunta rl = new Ryhmaliikunta(); 
    rl.parse("   1   |  4  |   kuntopiiri  | torstai | 18.00 "); 
    assertEquals("From: Ryhmaliikunta line: 232", 4, rl.getAsiakasNro()); 
    assertEquals("From: Ryhmaliikunta line: 233", "1|4|kuntopiiri|torstai|18.00", rl.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone269 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone269() throws CloneNotSupportedException {    // Ryhmaliikunta: 269
    Ryhmaliikunta har = new Ryhmaliikunta(); 
    har.parse("   2   |  10  |   Kalastus  | 1949 | 22 t "); 
    Ryhmaliikunta kopio = har.clone(); 
    assertEquals("From: Ryhmaliikunta line: 274", har.toString(), kopio.toString()); 
    har.parse("   1   |  11  |   Uinti  | 1949 | 22 t "); 
    assertEquals("From: Ryhmaliikunta line: 276", false, kopio.toString().equals(har.toString())); 
  } // Generated by ComTest END
}