package kuntosali.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kuntosali.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.19 15:40:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RyhmaliikuntaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi86 */
  @Test
  public void testRekisteroi86() {    // Ryhmaliikunta: 86
    Ryhmaliikunta testi1 = new Ryhmaliikunta(); 
    assertEquals("From: Ryhmaliikunta line: 88", 0, testi1.getTunnusNro()); 
    testi1.rekisteroi(); 
    Ryhmaliikunta testi2 = new Ryhmaliikunta(); 
    testi2.rekisteroi(); 
    int n1 = testi1.getTunnusNro(); 
    int n2 = testi2.getTunnusNro(); 
    assertEquals("From: Ryhmaliikunta line: 94", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse144 */
  @Test
  public void testParse144() {    // Ryhmaliikunta: 144
    Ryhmaliikunta rl = new Ryhmaliikunta(); 
    rl.parse("   1   |  4  |   kuntopiiri  | torstai | 18.00 "); 
    assertEquals("From: Ryhmaliikunta line: 147", 4, rl.getAsiakasNro()); 
    assertEquals("From: Ryhmaliikunta line: 148", "1|4|kuntopiiri|torstai|18.00", rl.toString()); 
  } // Generated by ComTest END
}