package kuntosali.test;
// Generated by ComTest BEGIN
import java.io.File;
import kuntosali.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.08.03 14:25:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RyhmaliikunnatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta48 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta48() throws SailoException {    // Ryhmaliikunnat: 48
    Ryhmaliikunnat harrasteet = new Ryhmaliikunnat(); 
    Ryhmaliikunta pitsi21 = new Ryhmaliikunta(); pitsi21.taytaRyhmaliikunta(1); 
    Ryhmaliikunta pitsi11 = new Ryhmaliikunta(); pitsi11.taytaRyhmaliikunta(1); 
    Ryhmaliikunta pitsi22 = new Ryhmaliikunta(); pitsi22.taytaRyhmaliikunta(1); 
    Ryhmaliikunta pitsi12 = new Ryhmaliikunta(); pitsi12.taytaRyhmaliikunta(1); 
    Ryhmaliikunta pitsi23 = new Ryhmaliikunta(); pitsi23.taytaRyhmaliikunta(1); 
    String tiedNimi = "testiryhmat.dat"; 
    File ftied = new File(tiedNimi); 
    ftied.delete(); 
    try {
    harrasteet.lueTiedostosta(tiedNimi); 
    fail("Ryhmaliikunnat: 61 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    harrasteet.lisaa(pitsi21); 
    harrasteet.lisaa(pitsi11); 
    harrasteet.lisaa(pitsi22); 
    harrasteet.lisaa(pitsi12); 
    harrasteet.lisaa(pitsi23); 
    harrasteet.tallenna(tiedNimi); 
    harrasteet = new Ryhmaliikunnat(); 
    harrasteet.lueTiedostosta(tiedNimi); 
    Iterator<Ryhmaliikunta> i = harrasteet.iterator(); 
    assertEquals("From: Ryhmaliikunnat line: 71", pitsi21.toString(), i.next().toString()); 
    assertEquals("From: Ryhmaliikunnat line: 72", pitsi11.toString(), i.next().toString()); 
    assertEquals("From: Ryhmaliikunnat line: 73", pitsi22.toString(), i.next().toString()); 
    assertEquals("From: Ryhmaliikunnat line: 74", pitsi12.toString(), i.next().toString()); 
    assertEquals("From: Ryhmaliikunnat line: 75", pitsi23.toString(), i.next().toString()); 
    assertEquals("From: Ryhmaliikunnat line: 76", false, i.hasNext()); 
    harrasteet.lisaa(pitsi23); 
    harrasteet.tallenna(tiedNimi); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTallenna120 
   * @throws SailoException when error
   */
  @Test
  public void testTallenna120() throws SailoException {    // Ryhmaliikunnat: 120
    Ryhmaliikunnat harrasteet = new Ryhmaliikunnat(); 
    Ryhmaliikunta pitsi21 = new Ryhmaliikunta(); pitsi21.taytaRyhmaliikunta(1); 
    Ryhmaliikunta pitsi11 = new Ryhmaliikunta(); pitsi11.taytaRyhmaliikunta(1); 
    Ryhmaliikunta pitsi22 = new Ryhmaliikunta(); pitsi22.taytaRyhmaliikunta(1); 
    Ryhmaliikunta pitsi12 = new Ryhmaliikunta(); pitsi12.taytaRyhmaliikunta(1); 
    Ryhmaliikunta pitsi23 = new Ryhmaliikunta(); pitsi23.taytaRyhmaliikunta(1); 
    String tiedNimi = "testiryhmat.dat"; 
    File ftied = new File(tiedNimi); 
    ftied.delete(); 
    try {
    harrasteet.lueTiedostosta(tiedNimi); 
    fail("Ryhmaliikunnat: 133 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    harrasteet.lisaa(pitsi21); 
    harrasteet.lisaa(pitsi11); 
    harrasteet.lisaa(pitsi22); 
    harrasteet.lisaa(pitsi12); 
    harrasteet.lisaa(pitsi23); 
    harrasteet.tallenna(tiedNimi); 
    harrasteet = new Ryhmaliikunnat(); 
    harrasteet.lueTiedostosta(tiedNimi); 
    Iterator<Ryhmaliikunta> i = harrasteet.iterator(); 
    assertEquals("From: Ryhmaliikunnat line: 143", pitsi21.toString(), i.next().toString()); 
    assertEquals("From: Ryhmaliikunnat line: 144", pitsi11.toString(), i.next().toString()); 
    assertEquals("From: Ryhmaliikunnat line: 145", pitsi22.toString(), i.next().toString()); 
    assertEquals("From: Ryhmaliikunnat line: 146", pitsi12.toString(), i.next().toString()); 
    assertEquals("From: Ryhmaliikunnat line: 147", pitsi23.toString(), i.next().toString()); 
    assertEquals("From: Ryhmaliikunnat line: 148", false, i.hasNext()); 
    harrasteet.lisaa(pitsi23); 
    harrasteet.tallenna(tiedNimi); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator210 */
  @Test
  public void testIterator210() {    // Ryhmaliikunnat: 210
    Ryhmaliikunnat ryhmat = new Ryhmaliikunnat(); 
    Ryhmaliikunta pitsi21 = new Ryhmaliikunta(2); ryhmat.lisaa(pitsi21); 
    Ryhmaliikunta pitsi11 = new Ryhmaliikunta(1); ryhmat.lisaa(pitsi11); 
    Ryhmaliikunta pitsi22 = new Ryhmaliikunta(2); ryhmat.lisaa(pitsi22); 
    Ryhmaliikunta pitsi12 = new Ryhmaliikunta(1); ryhmat.lisaa(pitsi12); 
    Ryhmaliikunta pitsi23 = new Ryhmaliikunta(2); ryhmat.lisaa(pitsi23); 
    Iterator<Ryhmaliikunta> i2=ryhmat.iterator(); 
    assertEquals("From: Ryhmaliikunnat line: 222", pitsi21, i2.next()); 
    assertEquals("From: Ryhmaliikunnat line: 223", pitsi11, i2.next()); 
    assertEquals("From: Ryhmaliikunnat line: 224", pitsi22, i2.next()); 
    assertEquals("From: Ryhmaliikunnat line: 225", pitsi12, i2.next()); 
    assertEquals("From: Ryhmaliikunnat line: 226", pitsi23, i2.next()); 
    try {
    assertEquals("From: Ryhmaliikunnat line: 227", pitsi12, i2.next()); 
    fail("Ryhmaliikunnat: 227 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int anrot[] = { 2,1,2,1,2} ; 
    for ( Ryhmaliikunta ryhma:ryhmat ) {
    assertEquals("From: Ryhmaliikunnat line: 233", anrot[n], ryhma.getAsiakasNro()); n++; 
    }
    assertEquals("From: Ryhmaliikunnat line: 236", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista285 
   * @throws SailoException when error
   */
  @Test
  public void testPoista285() throws SailoException {    // Ryhmaliikunnat: 285
    Ryhmaliikunnat harrasteet = new Ryhmaliikunnat(); 
    Ryhmaliikunta pitsi21 = new Ryhmaliikunta(); pitsi21.taytaRyhmaliikunta(2); 
    Ryhmaliikunta pitsi11 = new Ryhmaliikunta(); pitsi11.taytaRyhmaliikunta(1); 
    Ryhmaliikunta pitsi22 = new Ryhmaliikunta(); pitsi22.taytaRyhmaliikunta(2); 
    Ryhmaliikunta pitsi12 = new Ryhmaliikunta(); pitsi12.taytaRyhmaliikunta(1); 
    Ryhmaliikunta pitsi23 = new Ryhmaliikunta(); pitsi23.taytaRyhmaliikunta(2); 
    harrasteet.lisaa(pitsi21); 
    harrasteet.lisaa(pitsi11); 
    harrasteet.lisaa(pitsi22); 
    harrasteet.lisaa(pitsi12); 
    assertEquals("From: Ryhmaliikunnat line: 298", false, harrasteet.poista(pitsi23)); assertEquals("From: Ryhmaliikunnat line: 298", 4, harrasteet.getLkm()); 
    assertEquals("From: Ryhmaliikunnat line: 299", true, harrasteet.poista(pitsi11)); assertEquals("From: Ryhmaliikunnat line: 299", 3, harrasteet.getLkm()); 
    List<Ryhmaliikunta> h = harrasteet.annaRyhmaliikunnat(1); 
    assertEquals("From: Ryhmaliikunnat line: 301", 1, h.size()); 
    assertEquals("From: Ryhmaliikunnat line: 302", pitsi12, h.get(0)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa320 
   * @throws SailoException when error
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testKorvaaTaiLisaa320() throws SailoException,CloneNotSupportedException {    // Ryhmaliikunnat: 320
    Ryhmaliikunnat harrastukset = new Ryhmaliikunnat(); 
    Ryhmaliikunta har1 = new Ryhmaliikunta(), har2 = new Ryhmaliikunta(); 
    har1.rekisteroi(); har2.rekisteroi(); 
    assertEquals("From: Ryhmaliikunnat line: 326", 0, harrastukset.getLkm()); 
    harrastukset.korvaaTaiLisaa(har1); assertEquals("From: Ryhmaliikunnat line: 327", 1, harrastukset.getLkm()); 
    harrastukset.korvaaTaiLisaa(har2); assertEquals("From: Ryhmaliikunnat line: 328", 2, harrastukset.getLkm()); 
    Ryhmaliikunta har3 = har1.clone(); 
    har3.aseta(2,"kkk"); 
    Iterator<Ryhmaliikunta> i2=harrastukset.iterator(); 
    assertEquals("From: Ryhmaliikunnat line: 332", har1, i2.next()); 
    harrastukset.korvaaTaiLisaa(har3); assertEquals("From: Ryhmaliikunnat line: 333", 2, harrastukset.getLkm()); 
    i2=harrastukset.iterator(); 
    Ryhmaliikunta h = i2.next(); 
    assertEquals("From: Ryhmaliikunnat line: 336", har3, h); 
    assertEquals("From: Ryhmaliikunnat line: 337", true, h == har3); 
    assertEquals("From: Ryhmaliikunnat line: 338", false, h == har1); 
  } // Generated by ComTest END
}