package kuntosali.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kuntosali.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.04 17:35:44 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RyhmaliikuntaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi64 */
  @Test
  public void testRekisteroi64() {    // Ryhmaliikunta: 64
    Ryhmaliikunta testi1 = new Ryhmaliikunta(); 
    assertEquals("From: Ryhmaliikunta line: 66", 0, testi1.getTunnusNro()); 
    testi1.rekisteroi(); 
    Ryhmaliikunta testi2 = new Ryhmaliikunta(); 
    testi2.rekisteroi(); 
    int n1 = testi1.getTunnusNro(); 
    int n2 = testi2.getTunnusNro(); 
    assertEquals("From: Ryhmaliikunta line: 72", n2-1, n1); 
  } // Generated by ComTest END
}